### ISSUE TITLE
wrong stats for generator

### ISSUE THREAD

**Issue by algrebe** [deep-compute/funcserver#54]
The stats at [this highlighted portion](https://github.com/deep-compute/funcserver/blob/b28304f26ff5182104504587e10a7cacc1050d7c/funcserver/funcserver.py#L332-L334) are not valid for generators. We need to capture more metrics for generators such as
- total time taken
- cancelled midway

**Comment by prashanthellina** [comment]
Not maintaining funcserver as `kwikapi` is now the preferred option. closing this.
