### ISSUE TITLE
Private members and methods in API are being exposed 

### ISSUE THREAD

**Issue by venugopal-kandru** [deep-compute/funcserver#58]
We should not expose methods or members which start with `_`.

```python
from funcserver import Server


class MyAPI(object):
    def __init__(self, server):
        # FIXME private variable should not be accessible via debug web console
        self._server = server

    def add(self, a, b):
        return a + b

    # FIXME private function should not be accessible via debug web console and RPCHandler
    def _sub(self, a, b):
        """
        supposed to be private
        """
        return a - b

class MyServer(Server):
    def prepare_api(self):
        return MyAPI(self)

if __name__ == '__main__':
    MyServer().start()
```

```bash
$ python test.py run --port 8888 --debug
```

```
$ curl 'http://localhost:8888/rpc/json?fn=add&a=1&b=2'
{"result": 3, "success": true}
$ # this shouldn't work !
$ curl 'http://localhost:8888/rpc/json?fn=_sub&a=1&b=2'
{"result": -1, "success": true}
```

![funcserver](https://cloud.githubusercontent.com/assets/1938871/24654806/fb51cd26-1958-11e7-9b33-d394a0a2681b.png)

**Comment by algrebe** [comment]
@prashanthellina regarding https://github.com/deep-compute/funcserver/blob/bc9d5dff3134807dce5c95b04bdd40daafdcf6ef/funcserver/funcserver.py#L295-L299

Is there a need to split by `.` ? If not, we can replace that logic and check for a `_` in the beginning.
This will work for the RPCHandler, but for the WSConnection that uses code.InteractiveInterpreter, we will have to think of something else.
