### ISSUE TITLE
Send request process time in response headers

### ISSUE THREAD

**Issue by venugopal-kandru** [deep-compute/funcserver#62]
Add a new response header called `X-Time-Taken` which has the request processing time in seconds.

request processing time is already being computed and writing to log file as a metric.
https://github.com/deep-compute/funcserver/blob/2e0485c30b0ba3ed10d15b6a0271ab0068163022/funcserver/funcserver.py#L347-L352

Need to send the same value in response headers.

**Comment by prashanthellina** [comment]
Not maintaining funcserver as `kwikapi` is now the preferred option. closing this.
