### ISSUE TITLE
python 3 compatibility

### ISSUE THREAD

**Issue by venugopal-kandru** [deep-compute/funcserver#63]

**Comment by IdavalapatiRamanjaneyulu** [comment]
@Rajendra-R  This will take mostly 20 minutes. Can you work on this if you find time.

**Comment by ghost** [comment]
* Currently we are working on high priority project so we pause work on this project.

**Comment by prashanthellina** [comment]
Not maintaining funcserver as `kwikapi` is now the preferred option. closing this.
