### ISSUE TITLE
msgpack unpackb

### ISSUE THREAD

**Issue by IdavalapatiRamanjaneyulu** [deep-compute/funcserver#66]
For deserialising data using msgpack we should use msgpack.unpackb.
I think [here](https://github.com/deep-compute/funcserver/blob/master/funcserver/funcserver.py#L447) it should be unpackb.

**Comment by ghost** [comment]
* Currently we are working on high priority project so we pause work on this project.

**Comment by prashanthellina** [comment]
Not maintaining funcserver as `kwikapi` is now the preferred option. closing this.
